# Generated by Django 2.2.7 on 2019-11-19 03:29

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='公開時間')),
                ('body', tinymce.models.HTMLField(verbose_name='body')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
